import { adminOrHigher, adminOrHigherOrSelf, moderatorOrHigherOrSelf } from '@/access'
import { isClientRoleEqual } from '@/access/utilities'
import type { CollectionConfig } from 'payload'

export const Accounts: CollectionConfig = {
  slug: 'user-accounts',
  admin: {
    group: 'Auth',
    hidden: ({ user }) => !isClientRoleEqual('admin', user),
  },
  access: {
    read: adminOrHigherOrSelf,
    update: adminOrHigherOrSelf, // only admin or user can update its account
    delete: adminOrHigherOrSelf, // only admin or user can delete its account
    create: () => false, // everyone can create new account
  },
  fields: [
    /*  id, createdAt, and updatedAt is autogenerated by Payload */
    /* Add more fields as you need */
    {
      name: 'userId',
      type: 'relationship',
      relationTo: 'users',
      required: true,
      index: true,
    },
    {
      name: 'accountId',
      type: 'text',
      required: true,
    },
    {
      name: 'providerId',
      type: 'text',
      required: true,
      index: true,
    },
    {
      name: 'accessToken',
      type: 'text',
    },
    {
      name: 'refreshToken',
      type: 'text',
    },
    {
      name: 'accessTokenExpiresAt',
      type: 'date',
    },
    {
      name: 'refreshTokenExpiresAt',
      type: 'date',
    },
    {
      name: 'scope',
      type: 'text',
    },
    {
      name: 'idToken',
      type: 'text',
    },
    {
      name: 'password',
      type: 'text',
    },
  ],
}
