import { adminOrHigherOrSelf, moderatorOrHigherOrSelf } from '@/access'
import { isClientRoleEqual } from '@/access/utilities'
import { adminGroups } from '@/lib/adminGroups'
import type { CollectionConfig } from 'payload'

export const Sessions: CollectionConfig = {
  slug: 'user-sessions',
  admin: {
    group: adminGroups.auth,
    hidden: ({ user }) => !isClientRoleEqual('admin', user),
  },
  access: {
    read: adminOrHigherOrSelf(),
    update: adminOrHigherOrSelf(), // only admin or user can update its account
    delete: adminOrHigherOrSelf(), // only admin or user can delete its account
    create: () => false, // everyone can create new account
  },
  fields: [
    /*  id, createdAt, and updatedAt is autogenerated by Payload */
    /* Add more fields as you need */
    {
      name: 'userId',
      type: 'relationship',
      relationTo: 'users',
      required: true,
      index: true,
    },
    {
      name: 'token',
      type: 'text',
      required: true,
      unique: true,
    },
    {
      name: 'expiresAt',
      type: 'date',
      required: true,
    },
    {
      name: 'ipAddress',
      type: 'text',
      index: true,
    },
    {
      name: 'userAgent',
      type: 'text',
    },
  ],
}
