import {
  adminOrHigherOrSelf,
  fieldAdminOrHigher,
  fieldModeratorOrHigher,
  moderatorOrHigherOrSelf,
  publicAccess,
  publicAccessField,
} from '@/access'
import { getRoleConfig, Role, userRoles } from '@/access/hierarchy'
import { fieldRoleOrHigher, isClientRoleEqualOrHigher } from '@/access/utilities'
import { auth } from '@/auth/auth'
import { adminGroups } from '@/lib/adminGroups'
import { APIError, type CollectionConfig } from 'payload'

// TODO:
// [] Add preview feature for offers in the admin panel

export const Users: CollectionConfig = {
  slug: 'users',
  labels: {
    singular: {
      en: 'User',
      pl: 'Użytkownik',
    },
    plural: {
      en: 'Users',
      pl: 'Użytkownicy',
    },
  },
  admin: {
    useAsTitle: 'email',
    group: adminGroups.auth,
    hidden: ({ user }) => !isClientRoleEqualOrHigher('moderator', user),
  },
  auth: {
    disableLocalStrategy: true, // We should disable this since we use Better Auth now
    strategies: [
      {
        name: 'better-auth',
        authenticate: async ({ headers, payload }) => {
          try {
            // 1. Get user session from Better Auth using request headers
            const userSession = await auth.api.getSession({ headers })

            // 2. If no session exists, return null (not authenticated)
            if (!userSession || !userSession.user) return { user: null }

            // 3. Fetch full user data from Payload database
            const userData = await payload.findByID({
              collection: 'users',
              id: userSession?.user?.id,
            })

            // 4. Return user data in the expected format
            return {
              user: {
                ...userData,
                collection: 'users',
              },
            }
          } catch (err) {
            payload.logger.error(err)
            return { user: null }
          }
        },
      },
    ],
  },
  endpoints: [
    {
      path: '/logout',
      method: 'post',
      handler: async (req) => {
        // 1. Call Better Auth signOut to invalidate the session
        await auth.api.signOut({
          headers: req.headers,
        })

        // 2. Return success response
        return Response.json(
          {
            message: 'Token revoked successfully',
          },
          {
            status: 200,
            headers: req.headers,
          },
        )
      },
    },
  ],
  access: {
    read: moderatorOrHigherOrSelf(),
    update: adminOrHigherOrSelf(), // only admin or user can update its account
    delete: adminOrHigherOrSelf(), // only admin or user can delete its account
    create: () => false, // no one can create users directly (happens via Better Auth)
  },

  hooks: {
    beforeChange: [
      async ({ req, data }) => {
        // Sync image field with profilePicture media URL
        if (data.profilePicture) {
          try {
            // Handle both ID and full object cases
            const pfpId =
              typeof data.profilePicture === 'object' ? data.profilePicture.id : data.profilePicture

            const pfp = await req.payload.findByID({
              collection: 'profile-pictures',
              id: pfpId,
            })

            if (pfp?.url) {
              data.image = pfp.url
            }
          } catch (error) {
            req.payload.logger.error({
              message: 'Error syncing profile image URL:',
              error: error instanceof Error ? error.message : String(error),
            })
          }
        } else if (data.profilePicture === null) {
          // Clear image when profilePicture is removed
          data.image = null
        }

        return data
      },
    ],
  },
  fields: [
    // id, createdAt, and updatedAt is autogenerated by Payload
    {
      name: 'profilePicture',
      type: 'upload',
      relationTo: 'profile-pictures',
      label: {
        en: 'Profile Picture',
        pl: 'Zdjęcie Profilowe',
      },
    },
    {
      name: 'role',
      type: 'select',
      options: [...userRoles],
      defaultValue: 'client',
      required: true,
      label: {
        en: 'Role',
        pl: 'Rola',
      },
      access: {
        read: publicAccessField,
        update: fieldAdminOrHigher,
      },
      admin: {
        position: 'sidebar',
        condition: (data, siblingData, { user }) => {
          // Only show role field to moderators and higher
          return isClientRoleEqualOrHigher('moderator', user)
        },
        components: {
          Field: '/components/payload/fields/roleSelect',
        },
      },
    },

    {
      name: 'name',
      type: 'text',
      required: true,
      index: true,
      label: {
        en: 'Name',
        pl: 'Imię',
      },
    },
    {
      name: 'email',
      type: 'text',
      required: true,
      unique: true,
      index: true,
      label: 'Email',
    },
    {
      name: 'emailVerified',
      type: 'checkbox',
      required: true,
      label: {
        en: 'Email Verified',
        pl: 'Email Zweryfikowany',
      },
      access: {
        read: publicAccessField,
        update: fieldAdminOrHigher,
      },
    },
    {
      name: 'image',
      type: 'text',
      label: {
        en: 'Image',
        pl: 'Obraz',
      },
      admin: {
        position: 'sidebar',
        description: {
          en: 'Better Auth URL to the user profile image',
          pl: 'URL Better Auth do zdjęcia profilowego użytkownika',
        },
        condition: (data, siblingsData, { user }) => {
          // Only show image field to moderators and higher
          return isClientRoleEqualOrHigher('moderator', user)
        },
      },
      access: {
        read: publicAccessField,
        update: () => false, // prevent manual updates since it's auto-synced
      },
    },
    {
      name: 'offers',
      type: 'join',
      collection: 'offers',
      on: 'user',
      label: false,
      admin: {
        description: {
          en: 'Here you can see all offers you have created.',
          pl: 'Tutaj możesz zobaczyć wszystkie oferty, które utworzyłeś.',
        },
        allowCreate: true,
        condition: (data, siblingsData, { user }) => {
          // show to mods, admins and service-providers
          return isClientRoleEqualOrHigher('service-provider', user)
        },
      },
    },
  ],
}
