import { adminOrHigherOrSelf } from '@/access'
import { isClientRoleEqual } from '@/access/utilities'
import type { CollectionConfig } from 'payload'

export const Verifications: CollectionConfig = {
  slug: 'user-verifications',
  admin: {
    group: 'Auth',
    hidden: ({ user }) => !isClientRoleEqual('admin', user),
  },
  access: {
    read: adminOrHigherOrSelf,
    update: adminOrHigherOrSelf, // only admin or user can update its account
    delete: adminOrHigherOrSelf, // only admin or user can delete its account
    create: () => false, // everyone can create new account
  },
  fields: [
    /*  id, createdAt, and updatedAt is autogenerated by Payload */
    /* Add more fields as you need */
    {
      name: 'identifier',
      type: 'text',
      required: true,
    },
    {
      name: 'value',
      type: 'text',
      required: true,
    },
    {
      name: 'expiresAt',
      type: 'date',
      required: true,
    },
  ],
}
