import type { Metadata } from 'next'

import type { Media, Page, Config, Offer, OfferUpload } from '../payload-types'

import { mergeOpenGraph } from './mergeOpenGraph'
import { getServerSideURL } from './getURL'

/**
 * The static, crawler-safe default preview card (1200×630 PNG), regenerated by
 * `scripts/og/generate-default-og.mjs`. Social crawlers — facebookexternalhit,
 * which powers Instagram/Facebook/WhatsApp link previews, plus iMessage, Slack,
 * Discord, LinkedIn, X — skip a missing image entirely and render WebP
 * unreliably, so any page without its own SEO image falls back to this.
 */
const DEFAULT_OG_IMAGE = {
  url: '/og-image.png',
  width: 1200,
  height: 630,
  type: 'image/png',
} as const

type OgImage = {
  url: string
  width?: number
  height?: number
  type?: string
}

/**
 * Resolve a doc's preview image to an absolute URL the crawler can actually
 * fetch. Uploads on Vercel Blob already carry an absolute URL, so we must NOT
 * prepend the server origin (doing so yields `https://site.plhttps://…blob…`,
 * a malformed URL that crawlers silently drop). Relative paths still get the
 * origin prepended. Width/height/type are forwarded when known — explicit
 * dimensions make the very first scrape render the image instead of skipping it.
 */
const resolveOgImage = (
  image?: Media | OfferUpload | Config['db']['defaultIDType'] | null,
): OgImage => {
  const serverUrl = getServerSideURL()

  if (image && typeof image === 'object' && 'url' in image && image.url) {
    const absolute = /^https?:\/\//i.test(image.url) ? image.url : serverUrl + image.url

    return {
      url: absolute,
      width: image.width ?? undefined,
      height: image.height ?? undefined,
      type: image.mimeType ?? undefined,
    }
  }

  return { ...DEFAULT_OG_IMAGE, url: serverUrl + DEFAULT_OG_IMAGE.url }
}

export const generateMeta = async (args: {
  doc: Partial<Page> | Partial<Offer> | null
}): Promise<Metadata> => {
  const { doc } = args

  const ogImage = resolveOgImage(doc?.meta?.image)

  const title = doc?.meta?.title ? doc?.meta?.title + ' | Eventizer' : 'Eventizer'
  const description = doc?.meta?.description || undefined

  return {
    description,
    openGraph: mergeOpenGraph({
      description: description || '',
      images: [ogImage],
      title,
      url:
        doc && 'slug' in doc && doc.slug
          ? Array.isArray(doc.slug)
            ? doc.slug.join('/')
            : doc.slug
          : doc && 'link' in doc && doc.link
            ? doc.link
            : '/',
    }),
    title,
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage.url],
    },
  }
}
