import type { Metadata } from 'next'

import type { Media, Page, Config, Offer, OfferUpload } from '../payload-types'

import { mergeOpenGraph } from './mergeOpenGraph'
import { getServerSideURL } from './getURL'

/**
 * The static, crawler-safe default preview card (1200×630 PNG), regenerated by
 * `scripts/og/generate-default-og.mjs`. Social crawlers — facebookexternalhit,
 * which powers Instagram/Facebook/WhatsApp link previews, plus iMessage, Slack,
 * Discord, LinkedIn, X — skip a missing image entirely and render WebP
 * unreliably, so any page without its own SEO image falls back to this.
 */
const DEFAULT_OG_IMAGE = {
  url: '/og-image.png',
  width: 1200,
  height: 630,
  type: 'image/png',
} as const

type OgImage = {
  url: string
  width?: number
  height?: number
  type?: string
}

/**
 * Resolve a doc's preview image to an absolute URL the crawler can actually
 * fetch. Uploads on Vercel Blob already carry an absolute URL, so we must NOT
 * prepend the server origin (doing so yields `https://site.plhttps://…blob…`,
 * a malformed URL that crawlers silently drop). Relative paths still get the
 * origin prepended. Width/height/type are forwarded when known — explicit
 * dimensions make the very first scrape render the image instead of skipping it.
 */
const resolveOgImage = (
  image?: Media | OfferUpload | Config['db']['defaultIDType'] | null,
): OgImage => {
  const serverUrl = getServerSideURL()

  if (image && typeof image === 'object' && 'url' in image && image.url) {
    const absolute = /^https?:\/\//i.test(image.url) ? image.url : serverUrl + image.url

    return {
      url: absolute,
      width: image.width ?? undefined,
      height: image.height ?? undefined,
      type: image.mimeType ?? undefined,
    }
  }

  return { ...DEFAULT_OG_IMAGE, url: serverUrl + DEFAULT_OG_IMAGE.url }
}

/**
 * Canonical path for a doc, as a root-relative URL that `metadataBase` resolves
 * to an absolute one. The homepage (`home`) is the site root `/`, not `/home`.
 * Callers that know a different mount point (e.g. offers live under
 * `/ogloszenia/<link>`) pass an explicit `url` instead of relying on this.
 */
const deriveCanonicalPath = (doc?: Partial<Page> | Partial<Offer> | null): string => {
  const slug = doc && 'slug' in doc ? doc.slug : undefined
  if (slug) {
    const s = Array.isArray(slug) ? slug.join('/') : slug
    if (s === 'home') return '/'
    return '/' + String(s).replace(/^\/+/, '')
  }
  const link = doc && 'link' in doc ? doc.link : undefined
  if (link) return '/' + String(link).replace(/^\/+/, '')
  return '/'
}

export const generateMeta = async (args: {
  doc: Partial<Page> | Partial<Offer> | null
  /** Explicit canonical path (root-relative or absolute); overrides the slug/link derivation. */
  url?: string
}): Promise<Metadata> => {
  const { doc, url: explicitUrl } = args

  const ogImage = resolveOgImage(doc?.meta?.image)

  // Avoid a doubled "Eventizer | Eventizer" when the doc title already brands itself.
  const rawTitle = doc?.meta?.title?.trim()
  const title = rawTitle ? (/eventizer/i.test(rawTitle) ? rawTitle : rawTitle + ' | Eventizer') : 'Eventizer'
  const description = doc?.meta?.description || undefined
  const url = explicitUrl ?? deriveCanonicalPath(doc)

  return {
    description,
    alternates: { canonical: url },
    openGraph: mergeOpenGraph({
      description: description || '',
      images: [{ ...ogImage, alt: title }],
      title,
      url,
    }),
    title,
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage.url],
    },
  }
}
