import { writeFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import {
  ROOT,
  listNotes,
  matchGlob,
  grepCode,
  routeExists,
  changedFilesSince,
  globToRegex,
  trackedFiles,
} from './lib.mjs'

const ZONES_DIR = 'eventizer-mind/map/zones'
const FLOWS_DIR = 'eventizer-mind/map/flows'
const INDEX_FILE = path.join(ROOT, 'eventizer-mind/map/index.md')

function resolveAnchor(anchor) {
  const i = anchor.indexOf(':')
  const kind = anchor.slice(0, i)
  const val = anchor.slice(i + 1)
  if (kind === 'glob') return matchGlob(val).length > 0
  if (kind === 'route') return routeExists(val)
  if (kind === 'symbol') return grepCode(val).length > 0
  return false
}

// soft-check that an enforcedBy ref points at something real
function enforcedByResolves(ref) {
  const clean = String(ref).replace(/^\[\[/, '').replace(/\]\]$/, '')
  if (clean.startsWith('test:')) {
    const key = clean.slice(5)
    return trackedFiles().some((f) => f.startsWith('tests/') && f.includes(key))
  }
  if (clean.startsWith('skill:')) {
    return existsSync(path.join(ROOT, '.claude/skills', clean.slice(6)))
  }
  return true
}

export function run() {
  const errors = []
  const gaps = []
  const warnings = []
  const rows = []
  const attic = []

  const zones = listNotes(ZONES_DIR).filter((n) => n.frontmatter.type === 'zone')
  const flows = listNotes(FLOWS_DIR).filter((n) => n.frontmatter.type === 'flow')

  for (const z of zones) {
    const fm = z.frontmatter
    const name = path.basename(z.file, '.md')
    if (fm.status === 'unmounted') {
      attic.push({ name, summary: fm.summary || '' })
      continue
    }
    const owns = fm.owns || {}
    const globs = owns.globs || []
    const anchors = owns.anchors || []
    const routes = owns.routes || []

    for (const g of globs) {
      if (matchGlob(g).length === 0) errors.push(`[${name}] glob matches no tracked file: ${g}`)
    }
    for (const a of anchors) {
      if (!resolveAnchor(a)) errors.push(`[${name}] anchor does not resolve: ${a}`)
    }
    for (const r of routes) {
      if (!routeExists(r)) errors.push(`[${name}] route not found: ${r}`)
    }

    const changed = changedFilesSince(fm.verifiedAt)
    let fresh = '✅ fresh'
    if (changed === null) {
      fresh = '⚠ stale (unverified)'
    } else {
      const rxs = globs.map(globToRegex)
      if (changed.some((f) => rxs.some((rx) => rx.test(f)))) fresh = '⚠ stale'
    }

    for (const inv of fm.invariants || []) {
      const eb = inv.enforcedBy || []
      if (eb.length === 0) {
        gaps.push(`[${name}] invariant has no enforcedBy: "${inv.rule}"`)
      } else {
        for (const ref of eb) {
          if (!enforcedByResolves(ref)) warnings.push(`[${name}] enforcedBy ref not found: ${ref}`)
        }
      }
    }

    rows.push({
      name,
      status: fm.status || 'active',
      fresh,
      summary: (fm.summary || '').replace(/\s+/g, ' ').trim(),
    })
  }

  for (const fl of flows) {
    const name = path.basename(fl.file, '.md')
    for (const step of fl.frontmatter.steps || []) {
      if (!resolveAnchor(step)) errors.push(`[flow:${name}] step anchor does not resolve: ${step}`)
    }
  }

  if (existsSync(path.dirname(INDEX_FILE))) {
    writeFileSync(INDEX_FILE, renderIndex(rows, gaps, attic))
  }

  for (const w of warnings) console.warn('WARN: ' + w)
  for (const g of gaps) console.warn('GAP:  ' + g)
  for (const e of errors) console.error('ERROR: ' + e)
  console.log(`\n🧠 mind:check — ${rows.length} zones · ${gaps.length} gaps · ${errors.length} errors`)

  return { errors, gaps, warnings, rows, attic }
}

function renderIndex(rows, gaps, attic) {
  rows.sort((a, b) => a.name.localeCompare(b.name))
  const out = []
  out.push('<!-- GENERATED by scripts/mind/generate.mjs — DO NOT HAND-EDIT. Run `pnpm mind:check`. -->')
  out.push('')
  out.push('# Eventizer Mind — Zone Index')
  out.push('')
  out.push('| Zone | Status | Freshness | Summary |')
  out.push('| --- | --- | --- | --- |')
  for (const r of rows) out.push(`| [[${r.name}]] | ${r.status} | ${r.fresh} | ${r.summary} |`)
  out.push('')
  out.push('## ⚠ Verification gaps')
  out.push('')
  out.push(gaps.length ? gaps.map((g) => `- ${g}`).join('\n') : '_None._')
  out.push('')
  out.push('## Attic (unmounted)')
  out.push('')
  out.push(attic.length ? attic.map((a) => `- [[${a.name}]] — ${a.summary}`).join('\n') : '_Empty._')
  out.push('')
  return out.join('\n')
}

const invokedDirectly = process.argv[1] && process.argv[1].endsWith(path.join('mind', 'generate.mjs'))
if (invokedDirectly) {
  const { errors } = run()
  if (errors.length > 0) process.exit(1)
}
