/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-vercel-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  integer,
  varchar,
  boolean,
  timestamp,
  numeric,
  jsonb,
  type AnyPgColumn,
  pgEnum,
} from '@payloadcms/db-vercel-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-vercel-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', [
  'admin',
  'moderator',
  'service-provider',
  'client',
])
export const enum_offers_status = pgEnum('enum_offers_status', ['draft', 'published'])
export const enum__offers_v_version_status = pgEnum('enum__offers_v_version_status', [
  'draft',
  'published',
])
export const enum_payload_folders_folder_type = pgEnum('enum_payload_folders_folder_type', [
  'media',
])

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    profilePicture: integer('profile_picture_id').references(() => profile_pictures.id, {
      onDelete: 'set null',
    }),
    role: enum_users_role('role').default('client'),
    name: varchar('name').notNull(),
    email: varchar('email').notNull(),
    emailVerified: boolean('email_verified').notNull().default(false),
    image: varchar('image'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('users_profile_picture_idx').on(columns.profilePicture),
    index('users_name_idx').on(columns.name),
    uniqueIndex('users_email_idx').on(columns.email),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
  ],
)

export const user_sessions = pgTable(
  'user_sessions',
  {
    id: serial('id').primaryKey(),
    userId: integer('user_id_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    token: varchar('token').notNull(),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    ipAddress: varchar('ip_address'),
    userAgent: varchar('user_agent'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('user_sessions_user_id_idx').on(columns.userId),
    uniqueIndex('user_sessions_token_idx').on(columns.token),
    index('user_sessions_ip_address_idx').on(columns.ipAddress),
    index('user_sessions_updated_at_idx').on(columns.updatedAt),
    index('user_sessions_created_at_idx').on(columns.createdAt),
  ],
)

export const user_accounts = pgTable(
  'user_accounts',
  {
    id: serial('id').primaryKey(),
    userId: integer('user_id_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    accountId: varchar('account_id').notNull(),
    providerId: varchar('provider_id').notNull(),
    accessToken: varchar('access_token'),
    refreshToken: varchar('refresh_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    scope: varchar('scope'),
    idToken: varchar('id_token'),
    password: varchar('password'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('user_accounts_user_id_idx').on(columns.userId),
    index('user_accounts_provider_id_idx').on(columns.providerId),
    index('user_accounts_updated_at_idx').on(columns.updatedAt),
    index('user_accounts_created_at_idx').on(columns.createdAt),
  ],
)

export const user_verifications = pgTable(
  'user_verifications',
  {
    id: serial('id').primaryKey(),
    identifier: varchar('identifier').notNull(),
    value: varchar('value').notNull(),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('user_verifications_updated_at_idx').on(columns.updatedAt),
    index('user_verifications_created_at_idx').on(columns.createdAt),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    alt: varchar('alt').notNull(),
    prefix: varchar('prefix').default('Media'),
    folder: integer('folder_id').references(() => payload_folders.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_user_idx').on(columns.user),
    index('media_folder_idx').on(columns.folder),
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const profile_pictures = pgTable(
  'profile_pictures',
  {
    id: serial('id').primaryKey(),
    uploadedBy: varchar('uploaded_by'),
    prefix: varchar('prefix').default('Profile Pictures'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('profile_pictures_uploaded_by_idx').on(columns.uploadedBy),
    index('profile_pictures_updated_at_idx').on(columns.updatedAt),
    index('profile_pictures_created_at_idx').on(columns.createdAt),
    uniqueIndex('profile_pictures_filename_idx').on(columns.filename),
  ],
)

export const offer_uploads = pgTable(
  'offer_uploads',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    description: varchar('description').notNull(),
    offer: integer('offer_id')
      .notNull()
      .references(() => offers.id, {
        onDelete: 'set null',
      }),
    prefix: varchar('prefix').default('Offer Uploads'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('offer_uploads_offer_idx').on(columns.offer),
    index('offer_uploads_updated_at_idx').on(columns.updatedAt),
    index('offer_uploads_created_at_idx').on(columns.createdAt),
    uniqueIndex('offer_uploads_filename_idx').on(columns.filename),
  ],
)

export const offers = pgTable(
  'offers',
  {
    id: serial('id').primaryKey(),
    _order: varchar('_order'),
    user: integer('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    title: varchar('title').default('Nowa oferta'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_offers_status('_status').default('draft'),
  },
  (columns) => [
    index('offers__order_idx').on(columns._order),
    index('offers_user_idx').on(columns.user),
    index('offers_updated_at_idx').on(columns.updatedAt),
    index('offers_created_at_idx').on(columns.createdAt),
    index('offers__status_idx').on(columns._status),
  ],
)

export const _offers_v = pgTable(
  '_offers_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => offers.id, {
      onDelete: 'set null',
    }),
    version__order: varchar('version__order'),
    version_user: integer('version_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title').default('Nowa oferta'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__offers_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => [
    index('_offers_v_parent_idx').on(columns.parent),
    index('_offers_v_version_version__order_idx').on(columns.version__order),
    index('_offers_v_version_version_user_idx').on(columns.version_user),
    index('_offers_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_offers_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_offers_v_version_version__status_idx').on(columns.version__status),
    index('_offers_v_created_at_idx').on(columns.createdAt),
    index('_offers_v_updated_at_idx').on(columns.updatedAt),
    index('_offers_v_latest_idx').on(columns.latest),
    index('_offers_v_autosave_idx').on(columns.autosave),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_folders_folder_type = pgTable(
  'payload_folders_folder_type',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_payload_folders_folder_type('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('payload_folders_folder_type_order_idx').on(columns.order),
    index('payload_folders_folder_type_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_folders.id],
      name: 'payload_folders_folder_type_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_folders = pgTable(
  'payload_folders',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    folder: integer('folder_id').references((): AnyPgColumn => payload_folders.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_folders_name_idx').on(columns.name),
    index('payload_folders_folder_idx').on(columns.folder),
    index('payload_folders_updated_at_idx').on(columns.updatedAt),
    index('payload_folders_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    'user-sessionsID': integer('user_sessions_id'),
    'user-accountsID': integer('user_accounts_id'),
    'user-verificationsID': integer('user_verifications_id'),
    mediaID: integer('media_id'),
    'profile-picturesID': integer('profile_pictures_id'),
    'offer-uploadsID': integer('offer_uploads_id'),
    offersID: integer('offers_id'),
    'payload-foldersID': integer('payload_folders_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_user_sessions_id_idx').on(columns['user-sessionsID']),
    index('payload_locked_documents_rels_user_accounts_id_idx').on(columns['user-accountsID']),
    index('payload_locked_documents_rels_user_verifications_id_idx').on(
      columns['user-verificationsID'],
    ),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_profile_pictures_id_idx').on(
      columns['profile-picturesID'],
    ),
    index('payload_locked_documents_rels_offer_uploads_id_idx').on(columns['offer-uploadsID']),
    index('payload_locked_documents_rels_offers_id_idx').on(columns.offersID),
    index('payload_locked_documents_rels_payload_folders_id_idx').on(columns['payload-foldersID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['user-sessionsID']],
      foreignColumns: [user_sessions.id],
      name: 'payload_locked_documents_rels_user_sessions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['user-accountsID']],
      foreignColumns: [user_accounts.id],
      name: 'payload_locked_documents_rels_user_accounts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['user-verificationsID']],
      foreignColumns: [user_verifications.id],
      name: 'payload_locked_documents_rels_user_verifications_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['profile-picturesID']],
      foreignColumns: [profile_pictures.id],
      name: 'payload_locked_documents_rels_profile_pictures_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['offer-uploadsID']],
      foreignColumns: [offer_uploads.id],
      name: 'payload_locked_documents_rels_offer_uploads_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['offersID']],
      foreignColumns: [offers.id],
      name: 'payload_locked_documents_rels_offers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['payload-foldersID']],
      foreignColumns: [payload_folders.id],
      name: 'payload_locked_documents_rels_payload_folders_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users = relations(users, ({ one }) => ({
  profilePicture: one(profile_pictures, {
    fields: [users.profilePicture],
    references: [profile_pictures.id],
    relationName: 'profilePicture',
  }),
}))
export const relations_user_sessions = relations(user_sessions, ({ one }) => ({
  userId: one(users, {
    fields: [user_sessions.userId],
    references: [users.id],
    relationName: 'userId',
  }),
}))
export const relations_user_accounts = relations(user_accounts, ({ one }) => ({
  userId: one(users, {
    fields: [user_accounts.userId],
    references: [users.id],
    relationName: 'userId',
  }),
}))
export const relations_user_verifications = relations(user_verifications, () => ({}))
export const relations_media = relations(media, ({ one }) => ({
  user: one(users, {
    fields: [media.user],
    references: [users.id],
    relationName: 'user',
  }),
  folder: one(payload_folders, {
    fields: [media.folder],
    references: [payload_folders.id],
    relationName: 'folder',
  }),
}))
export const relations_profile_pictures = relations(profile_pictures, () => ({}))
export const relations_offer_uploads = relations(offer_uploads, ({ one }) => ({
  offer: one(offers, {
    fields: [offer_uploads.offer],
    references: [offers.id],
    relationName: 'offer',
  }),
}))
export const relations_offers = relations(offers, ({ one }) => ({
  user: one(users, {
    fields: [offers.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations__offers_v = relations(_offers_v, ({ one }) => ({
  parent: one(offers, {
    fields: [_offers_v.parent],
    references: [offers.id],
    relationName: 'parent',
  }),
  version_user: one(users, {
    fields: [_offers_v.version_user],
    references: [users.id],
    relationName: 'version_user',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_folders_folder_type = relations(
  payload_folders_folder_type,
  ({ one }) => ({
    parent: one(payload_folders, {
      fields: [payload_folders_folder_type.parent],
      references: [payload_folders.id],
      relationName: 'folderType',
    }),
  }),
)
export const relations_payload_folders = relations(payload_folders, ({ one, many }) => ({
  folder: one(payload_folders, {
    fields: [payload_folders.folder],
    references: [payload_folders.id],
    relationName: 'folder',
  }),
  folderType: many(payload_folders_folder_type, {
    relationName: 'folderType',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    'user-sessionsID': one(user_sessions, {
      fields: [payload_locked_documents_rels['user-sessionsID']],
      references: [user_sessions.id],
      relationName: 'user-sessions',
    }),
    'user-accountsID': one(user_accounts, {
      fields: [payload_locked_documents_rels['user-accountsID']],
      references: [user_accounts.id],
      relationName: 'user-accounts',
    }),
    'user-verificationsID': one(user_verifications, {
      fields: [payload_locked_documents_rels['user-verificationsID']],
      references: [user_verifications.id],
      relationName: 'user-verifications',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    'profile-picturesID': one(profile_pictures, {
      fields: [payload_locked_documents_rels['profile-picturesID']],
      references: [profile_pictures.id],
      relationName: 'profile-pictures',
    }),
    'offer-uploadsID': one(offer_uploads, {
      fields: [payload_locked_documents_rels['offer-uploadsID']],
      references: [offer_uploads.id],
      relationName: 'offer-uploads',
    }),
    offersID: one(offers, {
      fields: [payload_locked_documents_rels.offersID],
      references: [offers.id],
      relationName: 'offers',
    }),
    'payload-foldersID': one(payload_folders, {
      fields: [payload_locked_documents_rels['payload-foldersID']],
      references: [payload_folders.id],
      relationName: 'payload-folders',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_offers_status: typeof enum_offers_status
  enum__offers_v_version_status: typeof enum__offers_v_version_status
  enum_payload_folders_folder_type: typeof enum_payload_folders_folder_type
  users: typeof users
  user_sessions: typeof user_sessions
  user_accounts: typeof user_accounts
  user_verifications: typeof user_verifications
  media: typeof media
  profile_pictures: typeof profile_pictures
  offer_uploads: typeof offer_uploads
  offers: typeof offers
  _offers_v: typeof _offers_v
  payload_kv: typeof payload_kv
  payload_folders_folder_type: typeof payload_folders_folder_type
  payload_folders: typeof payload_folders
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users: typeof relations_users
  relations_user_sessions: typeof relations_user_sessions
  relations_user_accounts: typeof relations_user_accounts
  relations_user_verifications: typeof relations_user_verifications
  relations_media: typeof relations_media
  relations_profile_pictures: typeof relations_profile_pictures
  relations_offer_uploads: typeof relations_offer_uploads
  relations_offers: typeof relations_offers
  relations__offers_v: typeof relations__offers_v
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_folders_folder_type: typeof relations_payload_folders_folder_type
  relations_payload_folders: typeof relations_payload_folders
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-vercel-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
